steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/scankey-repo/scankey-v1a1-backend:$SHORT_SHA"
      - "-f"
      - "backend/Dockerfile"
      - "backend"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/scankey-repo/scankey-v1a1-backend:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "scankey-v1a1-backend"
      - "--image"
      - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/scankey-repo/scankey-v1a1-backend:$SHORT_SHA"
      - "--region"
      - "europe-southwest1"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--service-account"
      - "scankey-run-sa@$PROJECT_ID.iam.gserviceaccount.com"

images:
  - "europe-southwest1-docker.pkg.dev/$PROJECT_ID/scankey-repo/scankey-v1a1-backend:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
